-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-02-24 12:51:56 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE alumno (
    id_estudiante  INTEGER NOT NULL,
    matricula      VARCHAR2(30 CHAR),
    dni            INTEGER,
    nombre         VARCHAR2(50 CHAR),
    fecha_grupo    DATE,
    grupo_id_grupo INTEGER NOT NULL
);

ALTER TABLE alumno ADD CONSTRAINT alumno_pk PRIMARY KEY ( id_estudiante );

CREATE TABLE auxiliar (
    id_auxiliar          INTEGER NOT NULL,
    fecha                DATE,
    profesor_id_profesor INTEGER NOT NULL,
    tfc_id_tfc           INTEGER NOT NULL
);

ALTER TABLE auxiliar ADD CONSTRAINT auxiliar_pk PRIMARY KEY ( id_auxiliar );

CREATE TABLE comite (
    id_comite          INTEGER NOT NULL,
    numero_tribunal    SMALLINT,
    lugar              VARCHAR2(50),
    numero_componentes INTEGER,
    tfc_id_tfc         INTEGER NOT NULL
);

ALTER TABLE comite ADD CONSTRAINT comite_pk PRIMARY KEY ( id_comite );

CREATE TABLE detalle_comite (
    id_detalle_c         INTEGER NOT NULL,
    fecha                DATE,
    profesor_id_profesor INTEGER NOT NULL,
    comite_id_comite     INTEGER NOT NULL
);

ALTER TABLE detalle_comite ADD CONSTRAINT detalle_comite_pk PRIMARY KEY ( id_detalle_c );

CREATE TABLE grupo (
    id_grupo           INTEGER NOT NULL,
    numero             SMALLINT,
    nombre             VARCHAR2(30 CHAR),
    numero_componentes INTEGER
);

ALTER TABLE grupo ADD CONSTRAINT grupo_pk PRIMARY KEY ( id_grupo );

CREATE TABLE profesor (
    id_profesor INTEGER NOT NULL,
    dni         INTEGER,
    nombre      VARCHAR2(60 CHAR),
    domicilio   VARCHAR2(70 CHAR)
);

ALTER TABLE profesor ADD CONSTRAINT profesor_pk PRIMARY KEY ( id_profesor );

CREATE TABLE tfc (
    id_tfc               INTEGER NOT NULL,
    tema                 VARCHAR2(50 CHAR),
    no_orden             INTEGER,
    fecha_comienzo       DATE,
    fecha_defensa        DATE,
    alumno_id_estudiante INTEGER NOT NULL,
    profesor_id_profesor INTEGER NOT NULL
);

ALTER TABLE tfc ADD CONSTRAINT tfc_pk PRIMARY KEY ( id_tfc );

ALTER TABLE alumno
    ADD CONSTRAINT alumno_grupo_fk FOREIGN KEY ( grupo_id_grupo )
        REFERENCES grupo ( id_grupo );

ALTER TABLE auxiliar
    ADD CONSTRAINT auxiliar_profesor_fk FOREIGN KEY ( profesor_id_profesor )
        REFERENCES profesor ( id_profesor );

ALTER TABLE auxiliar
    ADD CONSTRAINT auxiliar_tfc_fk FOREIGN KEY ( tfc_id_tfc )
        REFERENCES tfc ( id_tfc );

ALTER TABLE comite
    ADD CONSTRAINT comite_tfc_fk FOREIGN KEY ( tfc_id_tfc )
        REFERENCES tfc ( id_tfc );

ALTER TABLE detalle_comite
    ADD CONSTRAINT detalle_comite_comite_fk FOREIGN KEY ( comite_id_comite )
        REFERENCES comite ( id_comite );

ALTER TABLE detalle_comite
    ADD CONSTRAINT detalle_comite_profesor_fk FOREIGN KEY ( profesor_id_profesor )
        REFERENCES profesor ( id_profesor );

ALTER TABLE tfc
    ADD CONSTRAINT tfc_alumno_fk FOREIGN KEY ( alumno_id_estudiante )
        REFERENCES alumno ( id_estudiante );

ALTER TABLE tfc
    ADD CONSTRAINT tfc_profesor_fk FOREIGN KEY ( profesor_id_profesor )
        REFERENCES profesor ( id_profesor );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
